### ISSUE TITLE
Build Backed

### ISSUE THREAD

**Issue by angelxmoreno** [angelxmoreno/twitter-export#2]
- [X] create node app #4  #5 
- [x] integrate TypeOrm orm #6
- [x] create auth controllers #7 
- [x] create Twitter end points #8 
- [x] add caching layer #9 
- [ ] add api testing and swagger docs
